help:
  _target_: csp_bot.commands.HelpCommandModel

echo:
  _target_: csp_bot.commands.EchoCommandModel

schedule:
  _target_: csp_bot.commands.ScheduleCommandModel

status:
  _target_: csp_bot.commands.StatusCommandModel
