defaults:
  - commands@commands
  - modules@modules
  - override hydra/job_logging: custom
  - _self_

start:
  # Options passed to gateway.start function
  realtime: true
  block: true
  show: false
  rest: true
  ui: false

authenticate: False
port: 8000

gateway:
  _target_: csp_bot.Gateway
  modules:
    - /modules/bot
    - /modules/mount_rest
    - /modules/mount_controls
    - /modules/mount_channels_graph
    - /modules/mount_outputs
    - /modules/mount_api_key_middleware
  commands:
    - /commands/help
    - /commands/echo
    - /commands/schedule
    - /commands/status
  settings:
    PORT: ${port}
    AUTHENTICATE: ${authenticate}

hydra:
  run:
    dir: outputs/${oc.env:HOSTNAME,localhost}_${hydra.job.name}/${now:%Y-%m-%d}/${now:%H-%M-%S}
