# @package modules.bot.config
symphony:
  _target_: csp_bot.SymphonyConfig
  bot_name: ${bot_name}
  config:
    _target_: chatom.symphony.SymphonyConfig
    host: ${oc.env:SYMPHONY_HOST}
    bot_username: ${oc.env:SYMPHONY_BOT_USERNAME}
    bot_certificate_path: ${oc.env:SYMPHONY_CERT_PATH}
